name: Theo Moss
author: Theophilus Moss
baseurl: 
description: INFJ: The Advocate
github: http://www.github.com/tmoss4
twitter: 
facebook: https://www.facebook.com/theophilus.moss
linkedin: https://www.linkedin.com/in/tmoss4
email: moss.theophilus@gmail.com
location: 
disqus: theophilusmoss

##Make sure to edit the above fields, especially for disqus.

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
