# Site settings
name: Theo Moss
author: Theo Moss
title: "Theo's Blog"
subtitle: 
description: "INFJ: The Advocate"
slogan:
keywords:
language: 'en'

url: 
baseurl: 
urlimg: /images

github: http://www.github.com/tmoss4
facebook: https://www.facebook.com/theophilus.moss
linkedin: https://www.linkedin.com/in/tmoss4
email: moss.theophilus@gmail.com
location: 
disqus: theos-blog

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

#       ___                __      __  _
#      /   |  ____  ____ _/ /_  __/ /_(_)_________
#     / /| | / __ \/ __ `/ / / / / __/ / ___/ ___/
#    / ___ |/ / / / /_/ / / /_/ / /_/ / /__(__  )
#   /_/  |_/_/ /_/\__,_/_/\__, /\__/_/\___/____/      http://www.google.com/analytics/
#                        /____/
#
# used in _includes/footer_scripts

google_analytics_tracking_id: UA-88742570-4